export { default as AddFlashcard } from './AddFlashcard'
export { default as Flashcards } from './Flashcards'
export { default as Home } from './Home'
export { default as Login } from './Login'
// export { default as SetCategory } from './SetCategory'
export { default as NotFound } from './NotFound'
export { default as UserPage } from './UserPage'
// export { default as CategoryPage } from './CategoryPage'
